language: node_js
node_js:
  - "8"
  - "9"

before_script:
  - npm install -g gulp-cli
  
script:
  - gulp

jobs:
  include:
    - stage: deploy
      node_js: 9
      script: skip
      deploy:
        provider: azure_web_apps
        site: nodesample
      on: master
        
