# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- script: npm install

- task: gulp@0
  inputs:
    publishJUnitResults: true

- task: archiveFiles@1
  inputs:
    rootFolder: $(Build.SourcesDirectory)
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    ArtifactName: drop
    ArtifactType: Container

- task: AzureFileCopy@1
  inputs:
    SourcePath: deploy.sh
    ConnectedServiceNameSelector: ConnectedServiceNameARM
    ConnectedServiceNameARM: RMPM (afc11291-9826-46be-b852-70349146ddf8)
    Destination: AzureBlob
    StorageAccountRM: adventworks
    ContainerName: test
