# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- script: npm install

- task: gulp@0
  inputs:
    publishJUnitResults: true

- task: archiveFiles@1
  inputs:
    rootFolder: $(Build.SourcesDirectory)
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    ArtifactName: drop
    ArtifactType: Container

- task: AzureFileCopy@1
  inputs: 
    SourcePath: deploy.sh 
    ConnectedServiceNameSelector: ConnectedServiceNameARM 
    ConnectedServiceNameARM: "DTLQA (c94bda7a-0577-4374-9c53-0e46a9fb0f70)" 
    Destination: AzureBlob 
    StorageAccountRM: adventworks 
    ContainerName: test 
