apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: atbagga/nodejs-app 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atbagga/nodejs-app 
    spec:
      containers:
        - name: atbagga/nodejs-app 
          image: atbagga.azurecr.io/atbagga/nodejs-app 
          ports:
          - containerPort: 8080